### PR TITLE
Fix audit logs: fix user display && correctly handle ReBAC resource instances in test

### LINKED ISSUE #103: fix user identification in audit logs command && ReBAC resource instances not correctly handled in test run audit
When displaying differences in audit results, it currently shows `user_id` instead of `user_key`,

Difference and error views should display the `user_key`  instead of `user_id`.

Image

**ReBAC resource instances not correctly handled**

When a ReBAC check happens, and the resource instance is being checked using the convention of resource:resource_instance, the resource key does not show in the request part of the audit log but only in the debug response.

### PR DESCRIPTION
**Pull request by daveads**
Fixes the user identification display in difference and error views to show `user_key` instead of `user_id`

And also fixes run audit command failing to properly compare ReBAC decisions

Changes:
- Added debug information to DetailedAuditLog interface
- Updated normalizeDetailedLog to preserve debug information from audit logs
- Enhanced createPdpRequest to extract resource instance IDs from ReBAC debug data
 
closes #103

### CODE REVIEW

File: source/components/test/views/DifferenceResultView.tsx [hunk 1]
```diff
@@ -10,7 +10,7 @@ const DifferenceResultView: React.FC<DifferenceResultViewProps> = ({
 	result,
 }) => (
 	<>
-		<Text>User: {result.auditLog.user_id}</Text>
+		<Text>User: {result.auditLog.user_key}</Text>
```
[the remark this answers is not in the document]
Comment (gemanor) [reply source/components/test/views/DifferenceResultView.tsx:13]:
```suggestion
		<Text>User: {result.auditLog.user_key || result.auditLog. user_id}</Text>
```

File: source/components/test/views/ErrorResultView.tsx [hunk 2]
```diff
@@ -8,7 +8,7 @@ interface ErrorResultViewProps {
 
 const ErrorResultView: React.FC<ErrorResultViewProps> = ({ result }) => (
 	<>
-		<Text>User: {result.auditLog.user_id}</Text>
+		<Text>User: {result.auditLog.user_key}</Text>
```
Comment (gemanor) [inline source/components/test/views/ErrorResultView.tsx:11]:
```suggestion
		<Text>User: {result.auditLog.user_key || result.auditLog.user_id}</Text>
```

File: source/components/test/auditUtils.ts [hunk 3]
```diff
@@ -113,35 +114,45 @@ export const createPdpRequest = (log: DetailedAuditLog): PdpRequestData => {
...
 		}
 	} else {
-		// For normal resources, use the resource value
-		resourceKey = log.resource || '';
+		const isResourceInstance =
+			typeof log.resource === 'string' && log.resource.includes(':');
+
+		if (isResourceInstance) {
+			// For specific resource instances, use the entire string as key
+			resourceKey = log.resource || '';
```
Comment (gemanor) [inline source/components/test/auditUtils.ts:137]: This is an invalid condition. If it's resource instance it should be only parts[0]

File: source/components/test/auditUtils.ts [hunk 4]
```diff
@@ -113,35 +114,45 @@ export const createPdpRequest = (log: DetailedAuditLog): PdpRequestData => {
...
+
+			// If it's in format "type:id", also extract the ID part
+			const parts = resourceKey.split(':');
+			if (parts.length >= 2 && parts[1]) {
```
Comment (gemanor) [inline source/components/test/auditUtils.ts:141]: The parts here must be `>=2` because you already had a statement if the string includes `:`

The logic of this if statement is invalid + there's a possibility where the resource object will include `key` which is the resource instance ID

Please fix

**Review by gemanor — CHANGES_REQUESTED** [review]
Left some comments. Please fix and LMK when done

File: source/components/test/auditUtils.ts [hunk 5]
```diff
@@ -113,38 +114,53 @@ export const createPdpRequest = (log: DetailedAuditLog): PdpRequestData => {
...
+			resourceType = parts[0] || resourceType;
+			resourceId = parts[1] || '';
+		} else if (
+			context.resource &&
+			'key' in context.resource &&
+			context.resource.key
+		) {
+			resourceKey = context.resource.key.toString();
+		} else {
+			resourceKey = log.resource || '';
```
Comment (gemanor) [inline source/components/test/auditUtils.ts]: You don't need resource key if there's no resource key. Why would you add the key here?

File: source/components/test/auditUtils.ts [hunk 6]
```diff
@@ -113,38 +114,53 @@ export const createPdpRequest = (log: DetailedAuditLog): PdpRequestData => {
...
+		}
```
Comment (gemanor) [inline source/components/test/auditUtils.ts]:
```suggestion
		}
```

**Review by gemanor — APPROVED** [review]

File: source/components/test/auditUtils.ts [hunk 7]
```diff
@@ -113,38 +114,51 @@ export const createPdpRequest = (log: DetailedAuditLog): PdpRequestData => {
...
+			const parts = resourceKey.split(':');
+			resourceType = parts[0] || resourceType;
+			resourceId = parts[1] || '';
+		} else if (
+			context.resource &&
+			'key' in context.resource &&
+			context.resource.key
+		) {
+			resourceKey = context.resource.key.toString();
+		}
```
Comment (gemanor) [inline source/components/test/auditUtils.ts:151]:
```suggestion
		} else {
			resourceKey = log.resource;
		}
```

File: source/components/test/auditUtils.ts [hunk 8]
```diff
@@ -113,38 +114,53 @@ export const createPdpRequest = (log: DetailedAuditLog): PdpRequestData => {
...
+			resourceType = parts[0] || resourceType;
+			resourceId = parts[1] || '';
+		} else if (
+			context.resource &&
+			'key' in context.resource &&
+			context.resource.key
+		) {
+			resourceKey = context.resource.key.toString();
+		} else {
+			resourceKey = log.resource;
```
Comment (gemanor) [inline source/components/test/auditUtils.ts:152]:
```suggestion
			resourceKey = log.resource || '';
```
